version: 3;

volumes:
  postgres_volume:

services:
  m-chat-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4300:50051"
    depends_on:
      - pg
  pg:
    image: postgres:16-alpine3.20
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  migrator:
    build:
      context: .
      dockerfile: docker/migration.Dockerfile
    restart: on-failure
    environment:
      DB_HOST: db